# Linux version

language: generic
sudo: required
dist: trusty

os:
  - linux

install:
  - ./install.sh

script:
  - lazbuild ProjectEuler.lpi
  - ./ProjectEuler

notifications:
  email:
    on_success: never
    on_failure: always